// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACiOxVRYg2THpf0_C_7H51-EhmiwKPqsc',
    appId: '1:905912718093:web:b35dbc7c442b541c97d644',
    messagingSenderId: '905912718093',
    projectId: 'rentalapp-47ed7',
    authDomain: 'rentalapp-47ed7.firebaseapp.com',
    storageBucket: 'rentalapp-47ed7.appspot.com',
    measurementId: 'G-R8SDXY3G7F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsNcoBNVJsd9TO-ooIRCS-OXaaIWyo4uc',
    appId: '1:905912718093:android:200c09284a43738997d644',
    messagingSenderId: '905912718093',
    projectId: 'rentalapp-47ed7',
    storageBucket: 'rentalapp-47ed7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCC4Av8IudCHRI4DEJ0z5KF0qwRDOWAUIA',
    appId: '1:905912718093:ios:e1a310d3b88500e497d644',
    messagingSenderId: '905912718093',
    projectId: 'rentalapp-47ed7',
    storageBucket: 'rentalapp-47ed7.appspot.com',
    iosBundleId: 'com.example.rentalappadmin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCC4Av8IudCHRI4DEJ0z5KF0qwRDOWAUIA',
    appId: '1:905912718093:ios:e1a310d3b88500e497d644',
    messagingSenderId: '905912718093',
    projectId: 'rentalapp-47ed7',
    storageBucket: 'rentalapp-47ed7.appspot.com',
    iosBundleId: 'com.example.rentalappadmin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACiOxVRYg2THpf0_C_7H51-EhmiwKPqsc',
    appId: '1:905912718093:web:44b264a96312647997d644',
    messagingSenderId: '905912718093',
    projectId: 'rentalapp-47ed7',
    authDomain: 'rentalapp-47ed7.firebaseapp.com',
    storageBucket: 'rentalapp-47ed7.appspot.com',
    measurementId: 'G-5G8467ZGBQ',
  );
}
